{{- if .Values.pdfStorage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "warn-v2.fullname" . }}-pdfs
  labels:
    {{- include "warn-v2.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteMany]
  storageClassName: {{ .Values.pdfStorage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.pdfStorage.size }}
{{- end }}
