apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "warn-v2.fullname" . }}-snapshots
  labels:
    {{- include "warn-v2.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteMany]
  storageClassName: {{ .Values.snapshotStorage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.snapshotStorage.size }}
